import Head from 'next/head'
import { Container, Row, Col } from 'react-bootstrap'
import LoginCard from '../components/LoginCard'



export default function Home() {
  return (
    <div>
      <Head>
        <title>ESCROTO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="bg-smdark h-100 pt-5" fluid>
        <Row className="h-100 justify-content-center pt-5">
          <Col md={3}>
            <h1 className="main-title text-center text-white py-0">ESCROTO</h1>
            <h5 className="mb-4" style={{ color: "#cccccc"}}>Épico Simulador de Combate Randomico Otimizador de Tarefas Ordinárias</h5>
            <LoginCard/>
          </Col>
        </Row>
      </Container>
    </div>
  )
}
