import Head from 'next/head'
import { Container, Row, Col } from 'react-bootstrap'
import LoginCard from '../components/LoginCard'



export default function Home() {
  return (
    <div>
      <Head>
        <title>ESCROTO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="bg-smdark h-100 pt-5" fluid>
        <Row className="h-100 justify-content-center pt-5">
          <Col md={6} className="d-flex flex-column align-items-center">
            <div className="main-title text-center text-white py-0">ESCROTO</div>
            <div className="main-subtitle text-center mb-4" style={{ color: "#cccccc"}}>Épico Simulador de Combate Randomico Otimizador de Tarefas Ordinárias</div>
            <LoginCard/>
          </Col>
        </Row>
      </Container>
    </div>
  )
}
